Repository scorelab/OpenMF, pull requests merged in 2021-08, with the labels that each got.

#216 [Frontend]: Created Frontend Section for Extractor
  React-frontend/package.json
  React-frontend/src/App.js
  React-frontend/src/components/Extractor/CaseCard.js
  React-frontend/src/components/Extractor/DeviceCard.js
  React-frontend/src/components/Extractor/ExtractDataForm.js
  React-frontend/src/components/Extractor/ExtractDataModel.js
  React-frontend/src/components/Extractor/ExtractedCases.js
  React-frontend/src/components/Extractor/ExtractorLayout.js
  React-frontend/src/components/Extractor/ShowLiveDevices.js
  React-frontend/src/components/Extractor/Sidebar.js
  React-frontend/src/pages/Extractor/ExtractedCasesPage.js
  React-frontend/src/pages/Extractor/LiveDevices.js
  React-frontend/src/pages/HomePage.js
  React-frontend/src/pages/Management/CompletedTaskPage.js
  React-frontend/src/pages/Management/TodoTaskPage.js
  React-frontend/src/store/actions/device.js
  React-frontend/src/store/actions/extract.js
  React-frontend/src/store/actions/extractor.js
  React-frontend/src/store/actions/utils.js
  React-frontend/src/store/reducers/device.js
  React-frontend/src/store/reducers/extract.js
  React-frontend/src/store/store.js
  React-frontend/src/store/types/device.js
  React-frontend/src/store/types/extract.js
  flask-backend/api/routes/user.py
Labels: gsoc-2021, review required

#218 [Frontend-Backend]: Data Visualization of Cases
  React-frontend/package.json
  React-frontend/src/App.js
  React-frontend/src/components/Charts/BrowserCharts.js
  React-frontend/src/components/LoginForm.js
  React-frontend/src/components/Management/AnalyticsSidebar.js
  React-frontend/src/components/Management/BrowserReport.js
  React-frontend/src/components/Management/CaseVisualizer.js
  React-frontend/src/components/Management/FileExplorer.js
  React-frontend/src/components/Management/GeneralReport.js
  React-frontend/src/components/Management/LocationReport.js
  React-frontend/src/components/Management/Report.js
  React-frontend/src/components/Management/Sidebar.js
  React-frontend/src/components/RegisterForm.js
  React-frontend/src/components/Utils/CaseFolderButton.js
  React-frontend/src/components/Utils/SelectItem.js
  React-frontend/src/components/core/HomeLogo.js
  React-frontend/src/pages/Management/Report/DataVisualizer.js
  React-frontend/src/pages/Management/Report/ReportMain.js
  React-frontend/src/store/actions/auth.js
  React-frontend/src/store/actions/case.js
  React-frontend/src/store/actions/file.js
  React-frontend/src/store/actions/management.js
  React-frontend/src/store/reducers/case.js
  React-frontend/src/store/reducers/file.js
  React-frontend/src/store/reducers/management.js
  React-frontend/src/store/types/case.js
  React-frontend/src/store/types/management.js
  flask-backend/api/__init__.py
  flask-backend/api/routes/case.py
  flask-backend/api/routes/extraction.py
  flask-backend/api/routes/report.py
  scripts/location.py
Labels: gsoc-2021, review required

#221 Modify data extract form
  React-frontend/src/components/Extractor/ExtractDataForm.js
  React-frontend/src/store/actions/extract.js
  flask-backend/api/routes/extraction.py
Labels: gsoc-2021, review required

#228 [Bug-Frontend]: Replaced Data-Grid to Custom Table
  React-frontend/src/components/Admin/ShowMembers.js
  React-frontend/src/components/Utils/TablePaginationActions.js
Labels: bug, gsoc-2021, review required

#223 Data visualization between two cases
  React-frontend/src/App.js
  React-frontend/src/components/Management/Analytics.js
  React-frontend/src/components/Management/AnalyticsSidebar.js
  React-frontend/src/components/Management/Compare.js
  React-frontend/src/pages/Management/ComparePage.js
  React-frontend/src/store/actions/management.js
  React-frontend/src/store/reducers/management.js
  React-frontend/src/store/types/management.js
  flask-backend/api/__init__.py
  flask-backend/api/routes/commonreport.py
  scripts/message.py
  scripts/phone.py
Labels: gsoc-2021, review required

#226 Email Verification and Forgot Password Implementation
  React-frontend/src/App.js
  React-frontend/src/components/Extractor/Sidebar.js
  React-frontend/src/components/LoginForm.js
  React-frontend/src/components/Management/Sidebar.js
  React-frontend/src/components/Sidebar.js
  React-frontend/src/components/Utils/VerifyButton.js
  React-frontend/src/components/core/ForgotPassword.js
  React-frontend/src/components/core/ResetPassword.js
  React-frontend/src/pages/ForgotPassword.js
  React-frontend/src/pages/ResetPassword.js
  React-frontend/src/pages/VerifyEmail.js
  React-frontend/src/store/actions/admin.js
  React-frontend/src/store/actions/auth.js
  React-frontend/src/store/reducers/auth.js
  React-frontend/src/store/types/auth.js
  flask-backend/.envsample
  flask-backend/api/__init__.py
  flask-backend/api/config.py
  flask-backend/api/extansions.py
  flask-backend/api/helpers/mail.py
  flask-backend/api/userAuthentication/auth.py
  flask-backend/endpoints.txt
  requirements.txt
Labels: gsoc-2021, review required

#229 Added some missing comments
  React-frontend/src/components/Management/FilterCase.js
  scripts/bluetooth.py
  scripts/browser.py
  scripts/fb_reader.py
  scripts/general_info.py
  scripts/media.py
  scripts/message.py
  scripts/phone.py
  scripts/wa_reader.py
Labels: gsoc-2021

#224 Analytics based on location
  React-frontend/src/App.js
  React-frontend/src/components/Management/AnalyticsSidebar.js
  React-frontend/src/components/Management/Location.js
  React-frontend/src/pages/Management/LocationPage.js
Labels: gsoc-2021, review required

#231 [Code Quality]: Added Comments to flask backend and React frontend
  React-frontend/src/components/Extractor/ExtractDataForm.js
  React-frontend/src/components/RegisterForm.js
  React-frontend/src/components/Sidebar.js
  React-frontend/src/components/core/Alert.js
  React-frontend/src/components/core/Footer.js
  React-frontend/src/components/core/Layout.js
  React-frontend/src/pages/AboutPage.js
  React-frontend/src/pages/ContactPage.js
  React-frontend/src/pages/LoginPage.js
  React-frontend/src/pages/NotFound.js
  React-frontend/src/pages/RegisterPage.js
  React-frontend/src/pages/admin/CreateTask.js
  React-frontend/src/pages/admin/MemberList.js
  React-frontend/src/pages/admin/ShowTasks.js
  React-frontend/src/store/actions/alerts.js
  React-frontend/src/store/reducers/alerts.js
  React-frontend/src/store/reducers/auth.js
  React-frontend/src/store/reducers/users.js
  React-frontend/src/store/types/auth.js
  flask-backend/api/config.py
  flask-backend/api/extansions.py
  flask-backend/api/models/admin.py
  flask-backend/api/models/base_user.py
  flask-backend/api/models/case.py
  flask-backend/api/models/extractor.py
  flask-backend/api/models/management.py
  flask-backend/api/models/task.py
  flask-backend/api/models/token_blacklist.py
  flask-backend/api/routes/extraction.py
  flask-backend/api/routes/task.py
  flask-backend/api/routes/user.py
  flask-backend/api/userAuthentication/auth.py
  flask-backend/api/utils/jwt_decorators.py
  flask-backend/api/utils/result.py
Labels: gsoc-2021, review required

#233 [Documentation]: Updated Flask Backend Readme.
  React-frontend/Readme.md
  flask-backend/Readme.md
Labels: gsoc-2021, review required

#236 Added Store Methods for other option inside ExtractAll apiutility Method
  apiUtility/apiUtils.py
Labels: gsoc-2021, review required

#238 [Frontend]: Added VerifyButton in AnalyticsSidebar.
  React-frontend/src/components/Management/AnalyticsSidebar.js
Labels: bug, review required
